version: '3'

services:
  robots-checker:
    image: robotstxt/checker-api:${IMAGE_TAG}
    ports:
      - 127.0.0.1:9080:8080
    hostname: robots-checker
    container_name: robots-checker
    depends_on:
      - robots-postgresql
      - robots-redis
    environment:
      DATASOURCE_URL: "jdbc:postgresql://robots-postgresql:5432/robotstxt"
      SPRING_REDIS_SENTINEL_MASTER: mymaster
      SPRING_REDIS_SENTINEL_NODES: robots-redis-sentinel:26379
    restart: on-failure

  robots-crawler:
    image: robotstxt/crawler-api:${IMAGE_TAG}
    ports:
      - 127.0.0.1:9081:8080
    hostname: robots-crawler
    container_name: robots-crawler
    depends_on:
      - robots-postgresql
      - robots-redis
    environment:
      DATASOURCE_URL: "jdbc:postgresql://robots-postgresql:5432/robotstxt"
      SPRING_REDIS_SENTINEL_MASTER: mymaster
      SPRING_REDIS_SENTINEL_NODES: robots-redis-sentinel:26379
    restart: on-failure

  robots-downloader-1:
    image: robotstxt/downloader:${IMAGE_TAG}
    ports:
      - 127.0.0.1:9082:8080
    hostname: robots-downloader-1
    container_name: robots-downloader-1
    depends_on:
      - robots-postgresql
      - robots-redis
    environment:
      DATASOURCE_URL: "jdbc:postgresql://robots-postgresql:5432/robotstxt"
      SPRING_REDIS_SENTINEL_MASTER: mymaster
      SPRING_REDIS_SENTINEL_NODES: robots-redis-sentinel:26379
    restart: on-failure

  robots-downloader-2:
    image: robotstxt/downloader:${IMAGE_TAG}
    ports:
      - 127.0.0.1:9083:8080
    hostname: robots-downloader-2
    container_name: robots-downloader-2
    depends_on:
      - robots-postgresql
      - robots-redis
    environment:
      DATASOURCE_URL: "jdbc:postgresql://robots-postgresql:5432/robotstxt"
      SPRING_REDIS_SENTINEL_MASTER: mymaster
      SPRING_REDIS_SENTINEL_NODES: robots-redis-sentinel:26379
      STREAM_CONSUMER_NAME: "consumer-2"
    restart: on-failure

  robots-postgresql:
    image: postgres:9.6-alpine
    ports:
      - 127.0.0.1:5432:5432
    hostname: robots-postgresql
    container_name: robots-postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgresql}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: robotstxt
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    restart: on-failure

  robots-redis:
    image: bitnami/redis:5.0-debian-10
    hostname: robots-redis
    container_name: robots-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis-data:/bitnami
    restart: on-failure

  robots-redis-sentinel:
    image: bitnami/redis-sentinel:5.0-debian-10
    hostname: robots-redis-sentinel
    container_name: robots-redis-sentinel
    environment:
      - REDIS_MASTER_HOST=robots-redis
    ports:
      - 127.0.0.1:26379:26379
    depends_on:
      - robots-redis
    volumes:
      - redis-sentinel-data:/bitnami
    restart: on-failure

volumes:
  redis-sentinel-data:
    driver: local
  redis-data:
    driver: local
